databases:
  - name: AthleticHUB
    databaseName: athletichub23_production
    user: farik
    plan: free

services:
  - type: web
    name: AthleticHUB
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: athletichub23_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default