databases:
  - name: AthleticHUB
    databaseName: athletichub23_production
    user: farik

services:
  - type: web
    name: AthleticHUB
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: athletichub23_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false